### ISSUE TITLE
Overwriting table index in config.lua example

### ISSUE THREAD

**Issue by mschaffr** [Hobbes0927/hec-wildhorses#2]
Hey there,

just one hint for your example config lua:
```
        locations = {
            coords = vector3(-5931.86, -3014.2, -1.99),
            coords = vector3(-5126.08, -2744.38, -8.08),
            coords = vector3(-4204.92, -2562.65, 8.44),
        },
```

With this assignment, you provide your table "location" a column called "coords".
In the actual example, you overwrite the column property two times and there will only be one left.

You can completely remove the `coords =` assignment and leave it like this:
```
        locations = {
            vector3(-5931.86, -3014.2, -1.99),
            vector3(-5126.08, -2744.38, -8.08),
            vector3(-4204.92, -2562.65, 8.44),
        },
```

Have a great day!

**Comment by Hobbes0927** [comment]
Thanks!
